### ISSUE TITLE
Discover Project Modules Not Displaying Evenly

### ISSUE THREAD

**Issue by cityhick** [ITPrism/CrowdFunding#133]
![fb-screenshot](https://cloud.githubusercontent.com/assets/10523781/5792747/e4e5106e-9ef5-11e4-827f-47758e6cf156.jpg)

I have a sidebar theme module published to the Discover menu item. This is causing the discover project modules to display a row of 2, than a row of 1, than a row of 2, than a row of 1 all the way down the page. The display count (Items Limit) under options on menu item is set to 12. I am sure this a CSS issue - I just can't figure it out.

Any help is greatly appreciated! Thanks!

**Comment by ITPrism** [comment]
Hi,
Thank you for the post!

It is because I split the project in rows of number. The system creates blocks of thumbnails with number of elements.
In your case, I guess, it is a [thumbnail block] (http://getbootstrap.com/2.3.2/components.html#thumbnails) with three elements. If there is something on the right side, the third elements goes bottom.

I have just fixed that and it will be available in next release.
Now, I create one thumbnail block with all elements into it. So, the will be reordered properly.

Cheers,
Todor
