### ISSUE TITLE
Language bug

### ISSUE THREAD

**Issue by messagedj** [ITPrism/CrowdFunding#141]
COM_CROWDFUNDING_FIELD_DESCRIPTION is being used as project description and is in the same time used in the Update tab as your update field. 

both fields are not the same

**Comment by ITPrism** [comment]
Hi,
Thank you very much for the post!

I am going to fix it.

Best regards,
Todor

**Comment by messagedj** [comment]
no problem, 

could you tell me what you are up to with my to-do list and what your planning will be?


Op 16 mrt. 2015, om 20:38 heeft Todor Iliev <notifications@github.com> het volgende geschreven:

Hi,
Thank you very much for the post!

I am going to fix it.

Best regards,
Todor

**Comment by ssnobben** [comment]
So what is the to-do list ? can you share that so we know what will come and if its good features..I also looking for one feature that I would like to include..

All the best!

**Comment by ITPrism** [comment]
You can find more information about future release on the [public forum] (https://members.itprism.com/forum/public-forum).

Cheers,
T

**Comment by messagedj** [comment]
Sorry m8, but i am getting quite confused, and a bit worried about this last email you send me…

We agreed on the custom work you will be doing for us right? 






Op 17 mrt. 2015, om 16:30 heeft Todor Iliev <notifications@github.com> het volgende geschreven:

You can find more information about future release on the public forum <https://members.itprism.com/forum/public-forum>.

Cheers,
T

**Comment by ITPrism** [comment]
Hi Pieter,
Yes. I will do it. All will be OK.

I had enough time to do custom last day because I have provide support, to
fix bugs and to answer to messages :)
However, I have four free days from today to Sunday. I will try to do many
of the things in the list.

I guess it will be the same next week.

I have five free hours on Monday, on Tuesday and on Wednesday. I am free
from Thursday to Sunday.
The fifth free hours last days gone to provide support, to fix bugs and to
answer to messages. :)

I hope to do lots of the things that you need in next four days and to the
end of the next week.

Best regards,
Todor


On Thu, Mar 19, 2015 at 11:00 AM, messagedj <notifications@github.com>
wrote:

> Sorry m8, but i am getting quite confused, and a bit worried about this
> last email you send me…
>
> We agreed on the custom work you will be doing for us right?
>
>
>
>
>
>
> Op 17 mrt. 2015, om 16:30 heeft Todor Iliev <notifications@github.com>
> het volgende geschreven:
>
> You can find more information about future release on the public forum <
> https://members.itprism.com/forum/public-forum>.
>
> Cheers,
> T
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/ITPrism/CrowdFunding/issues/141#issuecomment-82414585>.
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ITPrism/CrowdFunding/issues/141#issuecomment-83428144>
> .
>



-- 
Best regards,
Todor Iliev
Web developer

My sites
--------------
http://itprism.com - Blog about Web Development, SEO, On-line Marketing,
Gamification, Internet Security and Free Joomla! extensions.
http://joomlafunding.com - Crowdfunding platform focused on Joomla!
projects.
Subscribe yourself to ITPrism newsletter <http://itprism.com/>. You will
receive last news about new extensions and upgrades.
