### ISSUE TITLE
Currencies file will not load 

### ISSUE THREAD

**Issue by wj694** [ITPrism/CrowdFunding#175]
I have tried over and over to get the currencies file to load and keep coming up with the same error : Error
Column count doesn't match value count at row 1 SQL=INSERT INTO #__crowdf_currencies (id, title, code, symbol, position) VALUES ()
 I have tried both Joomla 2.5.1  and 3.6x

I have the following loaded
Joomla
Bootstrap template
ITPrism Library
Crowdfunding
locations: cities populations over 150000

System Info:
PHP 5.5
MySQL 5.6.30-cll-lve
Apache
PHPIntl
added php.ini file to root with:
          magic_quotes_gpc = Off
          magic_quotes_runtime = Off
          magic_quotes_sybase = Off
           extension=php_curl.dll
Added to top of .htaccess file: SetEnv PHPRC /home/youruser/public_html/php.ini

I have also tried loading the currencies file as both a zip file and just the xml file itself 
I have also started over aprox 6 times and just figure out what the issue is

**Comment by ITPrism** [comment]
It was a problem with the column name. It has to be [code instead abbr](https://github.com/ITPrism/CrowdFunding-Resources/commit/77594339637cf2cd2f3fc057e70c71ce0bba10da).

I have just uploaded the new resource file currencies.zip
You can download it from [here](http://itprism.com/help/95-crowdfunding-documentation-faq#resources).

or [here](https://github.com/ITPrism/CrowdFunding-Resources)

I have just uploaded it in the CDN server.
You should wait several minutes before download currencies.zip because the CDN servers have to update their content. Check currencies.xml in currencies.zip that it contains **_<code>_** instead **_<abbr>_** to be sure that is latest file.

Alternatively, you can download the file from its github repository.

**Comment by wj694** [comment]
Yes, it worked thank you!!

**Comment by hmdadou** [comment]
I have exactly the same problem I've used the currencies.zip and currencies.xml still get the same error
Column count doesn't match value count at row 1
